---

- name: Download RKE2 and apply workaround
  include_role:
    name: rke2_common

- name: Install RKE2
  become: true
  shell: >
    INSTALL_RKE2_CHANNEL={{ rke2.version }} INSTALL_RKE2_TYPE=server /tmp/rke2_installer.sh
  register: rke2_install_result
  retries: 5
  delay: 10
  until: rke2_install_result.rc == 0

- name: Ensure RKE2 config directory exists
  become: true
  file:
    path: /etc/rancher/rke2
    state: directory

- name: Generate RKE2 server config
  become: true
  template:
    src: config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
  notify: Restart rke2-server   # only notify if the file changed

- name: Start and enable rke2-server
  become: true
  systemd:
    name: rke2-server
    enabled: true
    state: started
  retries: 3
  delay: 30

- name: Create .kube directory
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: '0750'

- name: Copy .kube/config
  copy:
    src: /etc/rancher/rke2/rke2.yaml
    dest: "~/.kube/config"
    remote_src: true
    mode: '0600'
  register: copy_result
  until: copy_result is succeeded
  retries: 10
  delay: 30

- name: Add /usr/local/bin,/var/lib/rancher/rke2/bin and ~/bin to PATH
  lineinfile:
    path: ~/.bashrc
    line: export PATH="/usr/local/bin:/var/lib/rancher/rke2/bin:~/bin:$PATH"
